Remove necessary character
rust-lang-cn/rust-by-example-cn pull request #160
Opened 2022-12-27 13:23 UTC by weartist

2022-12-27 13:31 UTC, YangFong commented on src/conversion.md
> + 和 [`Into`] 两个 trait。不过，即便常见的情况也可能会用到特别的 trait，尤其是从 `String` 转换到别的类型，以及把别的类型转换到 `String` 时。
3 和 4 可以在同一行

2022-12-27 13:40 UTC, YangFong requested changes
观察了一下，若是前一行结尾或后一行开头不是中文字符，那么这两行就不会消除换行符。

还需要调整。

2022-12-27 13:40 UTC, YangFong commented on src/conversion/string.md
> +我们经常需要把字符串转成数字。完成这项工作的标准手段是用 [`parse`] 函数。我们得提供要转换到的类型，这可以通过不使用类型推断，或者用 “涡轮鱼” 语法（turbo
50 和 51 需要合并

2022-12-27 13:40 UTC, YangFong commented on src/custom_types/constants.md
> +有个特例就是 `"string"` 字面量。它可以不经改动就被赋给一个 `static` 变量，因为它的类型标记：`&'static str` 就包含了所要求的生命周期 `'static`。其他的引用类型都必须特地声明，使之拥有`'static` 生命周期。这两种引用类型的差异似乎也无关紧要，因为无论如何，`static` 变量都得显式地声明。
一个之前遗留的格式问题。

```suggestion
有个特例就是 `"string"` 字面量。它可以不经改动就被赋给一个 `static` 变量，因为它的类型标记：`&'static str` 就包含了所要求的生命周期 `'static`。其他的引用类型都必须特地声明，使之拥有 `'static` 生命周期。这两种引用类型的差异似乎也无关紧要，因为无论如何，`static` 变量都得显式地声明。
```

2022-12-27 13:40 UTC, YangFong commented on src/custom_types/constants.md
> +有个特例就是 `"string"` 字面量。它可以不经改动就被赋给一个 `static` 变量，因为它的类型标记：`&'static str` 就包含了所要求的生命周期 `'static`。其他的引用类型都必须特地声明，使之拥有`'static` 生命周期。这两种引用类型的差异似乎也无关紧要，因为无论如何，`static` 变量都得显式地声明。
一个之前遗留的格式问题。

```suggestion
有个特例就是 `"string"` 字面量。它可以不经改动就被赋给一个 `static` 变量，因为它的类型标记：`&'static str` 就包含了所要求的生命周期 `'static`。其他的引用类型都必须特地声明，使之拥有 `'static` 生命周期。这两种引用类型的差异似乎也无关紧要，因为无论如何，`static` 变量都得显式地声明。
```

2022-12-27 14:25 UTC, weartist commented on src/conversion.md
> + 和 [`Into`] 两个 trait。不过，即便常见的情况也可能会用到特别的 trait，尤其是从 `String` 转换到别的类型，以及把别的类型转换到 `String` 时。
的确，这个很奇怪，4行开头还有一个小空格

2022-12-27 14:28 UTC, weartist commented
> 观察了一下，若是前一行结尾或后一行开头不是中文字符，那么这两行就不会消除换行符。
> 
> 还需要调整。

是的，目前的方案是如果前一行结尾是换行，且倒数第二个字符是中文，且下一行开头第一个字符是中文，替换换行符，遇到的确是符号的地方不太好判断

2022-12-27 14:30 UTC, YangFong commented
也可以，现在已经解决了阅读层面上的空格问题。

2022-12-27 14:35 UTC, YangFong commented on src/hello/print/fmt.md
> +### 动手试一试为上面的 `Color` 结构体实现 `fmt::Display`，应得到如下的输出结果：
这里是一个误判。`动手试一试` 是一个标题，但在其下方没有提供一个空行，所以也被合并了。

2022-12-27 15:03 UTC, weartist commented on src/hello/print/fmt.md
> +### 动手试一试为上面的 `Color` 结构体实现 `fmt::Display`，应得到如下的输出结果：
的确！

2022-12-28 02:10 UTC, YangFong approved these changes

2022-12-28 02:10 UTC, merged